slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: false
    debug_logging: false
    enable_interactive_mode: false
    throttle_scans: 1
    scan_queue_size: 10
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: scan
    map_file_name: ""
    resolution: 0.05
    mode: mapping
    transform_publish_period: 0.05
    map_update_interval: 1.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.174533
    loop_closure_search_radius: 3.0
    loop_closure_minimum_chain_size: 10
    loop_closure_minimum_refinement_response: 0.55
    loop_closure_minimum_score: 210.0
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
