rtabmap:
  ros__parameters:
    use_sim_time: false
    frame_id: base_link
    map_frame_id: map
    odom_frame_id: odom
    publish_tf: true
    approx_sync: false
    queue_size: 30
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_rgbd: false
    subscribe_stereo: false
    subscribe_scan: false
    subscribe_scan_cloud: true
    subscribe_user_data: false
    subscribe_odom_info: true
    scan_cloud_topic: /lidar/points
    rtabmap_args: "--RGBD/VoxelSize 0.1 --Reg/Strategy 1 --Icp/VoxelSize 0.1 --Rtabmap/DetectionRate 5 --Grid/FromDepth false --Grid/RangeMin 0.3 --Grid/RangeMax 30 --Grid/CellSize 0.05"

icp_odometry:
  ros__parameters:
    use_sim_time: false
    frame_id: base_link
    odom_frame_id: lidar_odom
    publish_tf: false
    approx_sync: false
    queue_size: 10
    voxel_size: 0.1
    icp/CorrespondenceRatio: 0.15
    icp/PointToPlane: true
    icp/MaxCorrespondenceDistance: 0.5
    icp/Iterations: 30
